apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: microservices
  labels:
    app: orders
    tier: backend
data:
  # Application Configuration
  NODE_ENV: "production"
  PORT: "8083"
  
  # Database Configuration (connection string will be in secrets)
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DB_NAME: "orders"
  
  # Redis Configuration (connection string will be in secrets)
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Service Discovery
  CATALOG_SERVICE_URL: "http://catalog-service:8082"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  
  # API Settings
  RATE_LIMIT_WINDOW_MS: "900000"  # 15 minutes in milliseconds
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Pagination Defaults
  DEFAULT_PAGE_SIZE: "10"
  MAX_PAGE_SIZE: "100"
  
  # Feature Flags
  ENABLE_CACHE: "true"
  CACHE_TTL: "3600"  # Time-to-live in seconds
  
  # CORS Settings
  ALLOWED_ORIGINS: "https://frontend.example.com,https://admin.example.com" 