apiVersion: v1
kind: Secret
metadata:
  name: orders-secrets
  namespace: microservices
  labels:
    app: orders
    tier: backend
type: Opaque
data:
  # Database credentials
  # Note: These are placeholder values - you should replace them with actual base64-encoded secrets
  # To encode: echo -n "your-actual-value" | base64
  MONGO_URI: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNy9vcmRlcnM=
  MONGO_USERNAME: dXNlcm5hbWU=  # username
  MONGO_PASSWORD: cGFzc3dvcmQ=  # password
  
  # Redis credentials
  REDIS_URI: cmVkaXM6Ly91c2VybmFtZTpwYXNzd29yZEByZWRpcy1zZXJ2aWNlOjYzNzk=
  REDIS_PASSWORD: cGFzc3dvcmQ=  # password
  
  # API keys for external services
  PAYMENT_API_KEY: eW91ci1wYXltZW50LWFwaS1rZXk=
  SHIPPING_API_KEY: eW91ci1zaGlwcGluZy1hcGkta2V5=
  
  # JWT secret for authentication
  JWT_SECRET: c3VwZXItc2VjcmV0LWp3dC1zZWNyZXQ=
  
  # Service-to-service authentication
  SERVICE_API_KEY: aW50ZXJuYWwtc2VydmljZS1hcGkta2V5 