image:
  repository: kong
  tag: 3.4.1-alpine

env:
  database: "postgres"
  pg_host: "kong-postgresql"
  pg_user: "kong"
  pg_password: "kong"
  pg_database: "kong"

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters:
    - http2

proxy:
  enabled: true
  tls:
    enabled: true
  annotations:
    konghq.com/plugins: rate-limiting,jwt-auth,cors,bot-detection

postgresql:
  enabled: true
  postgresUser: kong
  postgresPassword: kong
  postgresDatabase: kong
  service:
    port: 5432

plugins:
- name: rate-limiting
  config:
    minute: 100
    policy: local
- name: cors
  config:
    origins:
    - '*'
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    headers:
    - Accept
    - Authorization
    - Content-Type
    - Origin
    - X-Requested-With
    exposed_headers:
    - X-Auth-Token
    credentials: true
    max_age: 3600
- name: jwt-auth
  config:
    key_claim_name: kid
    claims_to_verify:
    - exp
    - nbf
- name: bot-detection
  config:
    deny: ["curl", "wget", "PostmanRuntime"] 