services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=Services_db
      # Add these for security in development
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
      - ./Docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - microservices-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - microservices-network

  catalog:
    build: 
      context: ./Docker/catalog
      dockerfile: Dockerfile
    container_name: catalog-container
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=development
      - PORT=8082
      - MONGODB_URI=mongodb://root:example@mongo:27017/Services_db?authSource=admin
      - REDIS_URI=redis://redis:6379
    env_file:
      - ./Docker/catalog/.env
    volumes:
      - ./Docker/catalog:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - microservices-network
    # Add healthcheck
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  orders:
    build: 
      context: ./Docker/orders
      dockerfile: Dockerfile
    container_name: orders-container
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=development
      - PORT=8083
      - MONGODB_URI=mongodb://root:example@mongo:27017/Services_db?authSource=admin
      - REDIS_URI=redis://redis:6379
    env_file:
      - ./Docker/orders/.env
    volumes:
      - ./Docker/orders:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./ecommerce-frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_CATALOG_API_URL=http://catalog:8082/api/v1/catalog
      - NEXT_PUBLIC_ORDERS_API_URL=http://orders:8083/api/v1/orders
    volumes:
      - ./ecommerce-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - catalog
      - orders
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    depends_on:
      - mongo
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data: