# syntax=docker/dockerfile:1

ARG NODE_VERSION=23.7.0
FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV=production
WORKDIR /usr/src/app


COPY package.json package-lock.json ./
RUN npm ci --omit=dev


COPY . .


USER node

EXPOSE 8082


CMD ["npm", "start"]
