services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=Services_db
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d  

  catalog:
    build: ./catalog
    container_name: catalog-container
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    env_file:
      - ./catalog/.env

  orders:
    build: ./orders
    container_name: orders-container
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    env_file:
      - ./orders/.env

volumes:
  mongo-data:
